name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main

env:
  AZ_RESOURCE_GROUP: ${{ vars.AZ_RESOURCE_GROUP }}
  AZ_CONTAINER_REGISTRY_NAME: ${{ vars.AZ_CONTAINER_REGISTRY_NAME }}
  AZ_CONTAINER_APP_NAME: ${{ vars.AZ_CONTAINER_APP_NAME }}
  AZ_IMAGE_NAME: ${{ vars.AZ_IMAGE_NAME }}
  AZ_IMAGE_VERSION_TAG: latest

  REACT_APP_PSEUDOBANK_URL: ${{ vars.REACT_APP_PSEUDOBANK_URL }}


jobs:
  Build-and-Push-Image:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}

    steps:
    - uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Build image
      run: |
        docker build . -t ${{ env.AZ_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.AZ_IMAGE_NAME }}:${{ env.AZ_IMAGE_VERSION_TAG }} \
        --build-arg REACT_APP_PSEUDOBANK_URL="${{ env.REACT_APP_PSEUDOBANK_URL }}"
    
    - name: Push image to ACR
      run: |
        az acr login --name ${{ env.AZ_CONTAINER_REGISTRY_NAME }}

        docker push ${{ env.AZ_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.AZ_IMAGE_NAME }}:${{ env.AZ_IMAGE_VERSION_TAG }}
          
  Update-Container-App:
    needs: Build-and-Push-Image
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Deploy to Azure Container App
    #   uses: azure/container-apps-deploy-action@v0
    #   with:
    #     acrName: ${{ env.AZ_CONTAINER_REGISTRY_NAME }}
    #     containerAppName: ${{ env.AZ_CONTAINER_APP_NAME }}
    #     resourceGroup: ${{ env.AZ_RESOURCE_GROUP }}
    #     imageToDeploy: ${{ env.AZ_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.AZ_IMAGE_NAME }}:${{ env.AZ_IMAGE_VERSION_TAG }}

    - name: Restart a Container App Revision
      run: |
        echo "Listing active revisions for ${{ env.AZ_CONTAINER_APP_NAME }}..."
        ACTIVE_REVISION=$(az containerapp revision list --name ${{ env.AZ_CONTAINER_APP_NAME }} --resource-group ${{ env.AZ_RESOURCE_GROUP }} \
          | jq -r '.[] | select(.properties.active == true) | .name')
        
        echo "Active revision: $ACTIVE_REVISION"
        
        if [ -n "$ACTIVE_REVISION" ]; then
          echo "Restarting active revision $ACTIVE_REVISION..."
          az containerapp revision restart --name ${{ env.AZ_CONTAINER_APP_NAME }} --resource-group ${{ env.AZ_RESOURCE_GROUP }} --revision $ACTIVE_REVISION
          echo "$ACTIVE_REVISION restarted successfully."
        else
          echo "No active revision found to restart."
        fi
  